name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Test Auth
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Test gosec
        run: gosec ./...
  
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Path to Staticcheck
        run: echo "${GOPATH:-$HOME/go}/bin" >> $GITHUB_PATH

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Formatting Test
        run: test -z $(go fmt ./...)

      - name: Linting Check
        run: staticcheck ./...

      
